# SPDX-License-Identifier: Apache-2.0
cmake_minimum_required(VERSION 3.21)
if(NOT WIRELINK_SOURCE_DIR OR NOT MATCHING_WLC OR NOT TEST_BINARY_DIR)
  message(FATAL_ERROR "Set WIRELINK_SOURCE_DIR, MATCHING_WLC and TEST_BINARY_DIR")
endif()
set(_source "${TEST_BINARY_DIR}/source")
set(_build "${TEST_BINARY_DIR}/build")
file(MAKE_DIRECTORY "${_source}")
file(WRITE "${_source}/product.wl" "version 1; import \"child.wl\";\n")
file(WRITE "${_source}/child.wl" "version 1; message State = 1 {}\n")
file(WRITE "${_source}/state.bind.wl" "profile version 1; latest State { delivery = reliable; }\n")
file(WRITE "${_source}/CMakeLists.txt" "cmake_minimum_required(VERSION 3.21)
project(import_dependency_check LANGUAGES C)
include(\"${WIRELINK_SOURCE_DIR}/cmake/WirelinkWlc.cmake\")
add_library(Wirelink::wirelink INTERFACE IMPORTED)
wirelink_wlc_generate_codec(TARGET codec SCHEMA product.wl)
wirelink_wlc_generate_runtime(TARGET protocol CODEC_TARGET codec PROFILE state.bind.wl)
")
function(build_and_read out_header)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target protocol_wlc_codegen
    RESULT_VARIABLE _result OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
  if(NOT _result STREQUAL "0")
    message(FATAL_ERROR "Generation failed: ${_stdout}${_stderr}")
  endif()
  file(READ "${_build}/wirelink-generated/codec/product.h" _codec)
  file(READ "${_build}/wirelink-generated/protocol/product_runtime.h" _runtime)
  set(${out_header} "${_codec}\n${_runtime}" PARENT_SCOPE)
endfunction()
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${_source}" -B "${_build}"
  "-DWIRELINK_WLC_EXECUTABLE=${MATCHING_WLC}" -DWIRELINK_WLC_AUTO_DOWNLOAD=OFF
  RESULT_VARIABLE _result OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
if(NOT _result STREQUAL "0")
  message(FATAL_ERROR "Configure failed: ${_stdout}${_stderr}")
endif()
build_and_read(_before)
# Work even with coarse timestamp filesystems and multi-config generators.
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1)
file(WRITE "${_source}/child.wl" "version 1; import \"leaf.wl\"; message State = 1 { required uint32 revision = 1; }\n")
file(WRITE "${_source}/leaf.wl" "version 1; message Leaf = 2 {}\n")
build_and_read(_after)
if(_before STREQUAL _after OR NOT _after MATCHES "leaf_t")
  message(FATAL_ERROR "Changing an imported schema did not regenerate the product")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1)
file(WRITE "${_source}/leaf.wl" "version 1; message Leaf = 2 { required uint32 nested_revision = 1; }\n")
build_and_read(_nested)
if(_after STREQUAL _nested OR NOT _nested MATCHES "nested_revision")
  message(FATAL_ERROR "New import edges were not tracked on the next build")
endif()
message(STATUS "Imported edits and newly added transitive edges regenerate code")
