# SPDX-License-Identifier: ISC
cmake_minimum_required(VERSION 3.21)
include("${WIRELINK_SOURCE_DIR}/cmake/WirelinkWlc.cmake")

if(MODE STREQUAL "explicit")
  set(WIRELINK_WLC_AUTO_DOWNLOAD OFF)
  _wirelink_wlc_resolve("${MATCHING_WLC}" _compiler)
  # The resolver normalizes Windows separators and relative components.
  get_filename_component(_expected "${MATCHING_WLC}" ABSOLUTE)
  if(NOT _compiler STREQUAL _expected)
    message(FATAL_ERROR "Explicit compiler was not retained")
  endif()
elseif(MODE STREQUAL "wrong-abi")
  set(WIRELINK_WLC_CODEGEN_ABI 27)
  _wirelink_wlc_resolve("${MATCHING_WLC}" _compiler)
elseif(MODE STREQUAL "offline")
  set(WIRELINK_WLC_AUTO_DOWNLOAD OFF)
  set(CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH FALSE)
  set(CMAKE_FIND_USE_CMAKE_SYSTEM_PATH FALSE)
  _wirelink_wlc_resolve("" _compiler)
elseif(MODE STREQUAL "check")
  foreach(_mode explicit wrong-abi offline)
    execute_process(COMMAND "${CMAKE_COMMAND}"
      "-DWIRELINK_SOURCE_DIR=${WIRELINK_SOURCE_DIR}"
      "-DMATCHING_WLC=${MATCHING_WLC}" "-DMODE=${_mode}"
      -P "${CMAKE_CURRENT_LIST_FILE}"
      RESULT_VARIABLE _result OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
    string(REGEX REPLACE "[ \r\n]+" " " _stderr "${_stderr}")
    if(_mode STREQUAL "explicit")
      if(NOT _result STREQUAL "0")
        message(FATAL_ERROR "Explicit resolution failed: ${_stdout}${_stderr}")
      endif()
    else()
      if(_result STREQUAL "0")
        message(FATAL_ERROR "${_mode} unexpectedly succeeded")
      endif()
      if(_mode STREQUAL "wrong-abi" AND NOT _stderr MATCHES "codegen ABI 27")
        message(FATAL_ERROR "Wrong failure: ${_stderr}")
      elseif(_mode STREQUAL "offline" AND NOT _stderr MATCHES "AUTO_DOWNLOAD is OFF")
        message(FATAL_ERROR "Wrong failure: ${_stderr}")
      endif()
    endif()
  endforeach()
  message(STATUS "WLC explicit, wrong-ABI and offline resolution checks passed")
else()
  message(FATAL_ERROR "Unknown resolution test mode")
endif()
