/* SPDX-License-Identifier: Apache-2.0 */
// Generated by WLC.
#pragma once
#include <device/types.hpp>
#include <wirelink/cpp/session.hpp>
#include <chrono>
#include <utility>

namespace device {
class Client {
public:
  static wirelink::Result<Client> connect(const wirelink::UdpOptions& options);
  Client(Client&&) noexcept = default;
  Client& operator=(Client&&) noexcept = default;
  Client(const Client&) = delete;
  Client& operator=(const Client&) = delete;
  wirelink::Result<ConfigureResponse> configure(const ConfigureRequest& request,
      std::chrono::milliseconds timeout = std::chrono::seconds(1));
  wirelink::Result<InfoResponse> get_info(const InfoRequest& request,
      std::chrono::milliseconds timeout = std::chrono::seconds(1));
  void close() noexcept { session_.close(); }
  bool is_open() const noexcept { return session_.is_open(); }
  std::uint16_t local_port() const noexcept { return session_.local_port(); }
private:
  explicit Client(wirelink::Session session) : session_(std::move(session)) {}
  wirelink::Session session_;
};
} // namespace device
