/* SPDX-License-Identifier: Apache-2.0 */
// Generated by WLC. All fields own their data.
#pragma once
#include <array>
#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace device {
enum class Mode : std::int32_t {
  MODE_IDLE = 0,
  MODE_ACTIVE = 1,
};

struct InfoRequest {
};

struct Settings {
  std::optional<std::string> label{};
  bool enabled{};
  std::optional<Mode> mode{};
  std::vector<std::uint8_t> token{};
  std::array<float, 3> gains{};
  std::optional<std::array<uint64_t, 2>> counters{};
  std::optional<int64_t> floor{};
  std::optional<uint64_t> ceiling{};
  std::optional<std::string> class_{};
  std::optional<uint16_t> timeout_{};
  std::string label_or_default() const { return label.value_or(std::string("\xE8""\xAE""\xBE""\xE5""\xA4""\x87", 6)); }
  Mode mode_or_default() const { return mode.value_or(static_cast<Mode>(1)); }
  int64_t floor_or_default() const { return floor.value_or((-INT64_C(9223372036854775807) - 1)); }
  uint64_t ceiling_or_default() const { return ceiling.value_or(UINT64_C(18446744073709551615)); }
};

struct InfoResponse {
  std::string name{};
  Settings settings{};
};

struct ConfigureRequest {
  Settings settings{};
  std::optional<std::vector<std::uint8_t>> opaque{};
  std::optional<Settings> backup{};
};

struct ConfigureResponse {
  Settings settings{};
  std::optional<std::vector<std::uint8_t>> opaque{};
  std::optional<Settings> backup{};
  uint32_t count{};
};

struct Numbers {
  int8_t i8{};
  uint8_t u8{};
  int16_t i16{};
  uint16_t u16{};
  int32_t i32{};
  uint32_t u32{};
  int64_t i64{};
  uint64_t u64{};
  uint32_t f32{};
  uint64_t f64{};
  float single{};
  double double_{};
  std::optional<std::array<double, 2>> doubles{};
  std::array<uint32_t, 2> words{};
  std::optional<int64_t> offset{};
  std::optional<int32_t> minimum{};
  std::optional<bool> flag{};
  std::optional<std::string> text{};
  int64_t offset_or_default() const { return offset.value_or(INT64_C(-7)); }
  int32_t minimum_or_default() const { return minimum.value_or(INT32_C(-2147483648)); }
  bool flag_or_default() const { return flag.value_or(true); }
  std::string text_or_default() const { return text.value_or(std::string("\x61""\x22""\x40""\x4E""\x41""\x4D""\x45""\x40", 8)); }
};

} // namespace device
