# SPDX-License-Identifier: Apache-2.0

core_version: str
codegen_abi: int
binding_api: int

class Error:
    @property
    def kind(self) -> str: ...
    @property
    def status(self) -> int: ...
    @property
    def rejection(self) -> int: ...
    @property
    def local_error(self) -> int: ...
    @property
    def transport_error(self) -> int: ...
    @property
    def runtime_error(self) -> int: ...
    @property
    def codec_error(self) -> int: ...
    @property
    def os_error(self) -> int: ...
    @property
    def os_message(self) -> str: ...

class Client:
    def close(self) -> None: ...
    @property
    def is_open(self) -> bool: ...
    @property
    def local_port(self) -> int: ...
    def add(self, left: int, right: int, timeout_ms: int) -> tuple[int, None] | tuple[None, Error]: ...

def connect(peer_address: str, peer_port: int, bind_address: str,
            bind_port: int) -> tuple[Client, None] | tuple[None, Error]: ...
