CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_UDC_DWC2_DMA=y
CONFIG_UART_LINE_CTRL=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n
CONFIG_SAMPLE_USBD_PID=0x574c
CONFIG_SAMPLE_USBD_PRODUCT="Wirelink RX benchmark"
