# SPDX-License-Identifier: Apache-2.0
CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_THREAD_RUNTIME_STATS_USE_TIMING_FUNCTIONS=y
CONFIG_THREAD_NAME=y
CONFIG_THREAD_MONITOR=y
CONFIG_PRINTK=y
CONFIG_ASSERT=y
CONFIG_LOG_BUFFER_SIZE=8192
CONFIG_SEGGER_RTT_BUFFER_SIZE_UP=16384
