/* SPDX-License-Identifier: Apache-2.0 */

#ifndef WIRELINK_VERSION_H_
#define WIRELINK_VERSION_H_

#define WIRELINK_VERSION_MAJOR 0
#define WIRELINK_VERSION_MINOR 9
#define WIRELINK_VERSION_PATCH 0
#define WIRELINK_VERSION_STRING "0.9.0"

#define WIRELINK_PROTOCOL_VERSION 1

#endif /* WIRELINK_VERSION_H_ */
