CONFIG_WIRELINK=y
CONFIG_TIMING_FUNCTIONS=y
CONFIG_CAN=n
CONFIG_PWM=n
CONFIG_LED=n
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_PRINTK=y
CONFIG_LOG=n
CONFIG_ASSERT=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_SPEED_OPTIMIZATIONS=y
# The ESP32-S3 Xtensa toolchain does not support LTO.
