/* SPDX-License-Identifier: Apache-2.0 */
// Generated by WLC.
#include <calculator/client.hpp>
#include "values.hpp"
#include "endpoint.h"
#include <memory>
#include <new>

namespace calculator {
using namespace wlc_native;
namespace {
void deallocate(void* pointer) noexcept {
  ::operator delete(pointer, std::align_val_t(calculator_sdk_endpoint_alignment()));
}
void* create(wl_endpoint_driver_t& driver, wirelink::Error& error) {
  std::unique_ptr<void, decltype(&deallocate)> endpoint(
      ::operator new(calculator_sdk_endpoint_size(), std::align_val_t(calculator_sdk_endpoint_alignment())), deallocate);
  const int status = calculator_sdk_endpoint_init(endpoint.get(), &driver);
  if (status != WL_OK) {
    error = wirelink::Error::local(status);
    return nullptr;
  }
  return endpoint.release();
}
void destroy(void* pointer) noexcept {
  calculator_sdk_endpoint_close(pointer);
  deallocate(pointer);
}
} // namespace

wirelink::Result<Client> Client::connect(const wirelink::UdpOptions& options) {
  auto session = wirelink::Session::connect(options, {create, destroy});
  if (!session) return session.error();
  return Client(std::move(session).value());
}

wirelink::Result<AddResponse> Client::add(const AddRequest& request,
    std::chrono::milliseconds timeout) {
  if (timeout.count() <= 0 || timeout.count() > INT32_MAX)
    return wirelink::Error::local(WL_ERR_INVALID_ARG);
  struct Call {
    add_request_value_t request{};
    add_response_value_t response{};
    std::uint32_t timeout_ms;
  } call;
  if (!wlc_detail::to_c(request, call.request))
    return wirelink::Error::local(WL_ERR_INVALID_ARG);
  call.timeout_ms = static_cast<std::uint32_t>(timeout.count());
  const auto completion = session_.invoke([](void* endpoint, void* context) noexcept {
    auto& state = *static_cast<Call*>(context);
    return calculator_sdk_add(endpoint,
        &state.request, &state.response, state.timeout_ms);
  }, &call);
  if (completion.status != WL_RPC_SUCCESS)
    return wirelink::Error::from_completion(completion);
  try {
    return wlc_detail::from_c(call.response);
  } catch (const std::bad_alloc&) {
    return wirelink::Error::local(WL_ERR_NO_MEM);
  }
}

} // namespace calculator
