/* SPDX-License-Identifier: Apache-2.0 */
// Generated by WLC. Python headers precede all system headers.
#include <nanobind/nanobind.h>
#include <nanobind/stl/array.h>
#include <nanobind/stl/string.h>
#include <calculator/client.hpp>
#include <wirelink/version.h>
namespace nb = nanobind;
using namespace calculator;

namespace {
[[maybe_unused]] AddRequest read_AddRequest(nb::handle object) {
  const auto input = nb::cast<nb::tuple>(object);
  if (input.size() != 2) nb::raise_type_error("invalid AddRequest tuple length");
  AddRequest output{};
    output.left = nb::cast<int32_t>(input[0]);
    output.right = nb::cast<int32_t>(input[1]);
  return output;
}

[[maybe_unused]] nb::tuple write_AddRequest(const AddRequest& input) {
  (void)input;
  return nb::make_tuple(
      nb::cast(input.left),
      nb::cast(input.right)
  );
}

[[maybe_unused]] AddResponse read_AddResponse(nb::handle object) {
  const auto input = nb::cast<nb::tuple>(object);
  if (input.size() != 1) nb::raise_type_error("invalid AddResponse tuple length");
  AddResponse output{};
    output.sum = nb::cast<int32_t>(input[0]);
  return output;
}

[[maybe_unused]] nb::tuple write_AddResponse(const AddResponse& input) {
  (void)input;
  return nb::make_tuple(
      nb::cast(input.sum)
  );
}

} // namespace

NB_MODULE(_native, module) {
  module.attr("core_version") = WIRELINK_VERSION_STRING;
  module.attr("codegen_abi") = 32;
  module.attr("binding_api") = 1;
  nb::class_<wirelink::Error>(module, "Error")
      .def_prop_ro("kind", [](const wirelink::Error& e) { return wirelink::error_kind_name(e.kind); })
      .def_prop_ro("status", [](const wirelink::Error& e) { return e.completion.status; })
      .def_prop_ro("rejection", [](const wirelink::Error& e) { return e.completion.rejection; })
      .def_prop_ro("local_error", [](const wirelink::Error& e) { return e.completion.local_error; })
      .def_prop_ro("transport_error", [](const wirelink::Error& e) { return e.completion.transport_error; })
      .def_prop_ro("runtime_error", [](const wirelink::Error& e) { return e.completion.runtime_error; })
      .def_prop_ro("codec_error", [](const wirelink::Error& e) { return e.completion.codec_error; })
      .def_prop_ro("os_error", [](const wirelink::Error& e) { return e.system_error.value(); })
      .def_prop_ro("os_message", [](const wirelink::Error& e) { return e.system_error.message(); });

  nb::class_<calculator::Client>(module, "Client")
      .def("close", &calculator::Client::close, nb::call_guard<nb::gil_scoped_release>())
      .def_prop_ro("is_open", &calculator::Client::is_open)
      .def_prop_ro("local_port", &calculator::Client::local_port)
      .def("add", [](calculator::Client& client, nb::tuple request, std::int64_t timeout_ms) {
        auto owned = read_AddRequest(request);
        auto result = [&] {
          nb::gil_scoped_release release;
          return client.add(owned, std::chrono::milliseconds(timeout_ms));
        }();
        if (!result) return nb::make_tuple(nb::none(), wirelink::Error(result.error()));
        return nb::make_tuple(write_AddResponse(result.value()), nb::none());
      })
      ;
  module.def("connect", [](const std::string& peer_address, std::uint16_t peer_port,
                           const std::string& bind_address, std::uint16_t bind_port) {
    auto result = [&] {
      nb::gil_scoped_release release;
      return calculator::Client::connect({peer_address, peer_port, bind_address, bind_port});
    }();
    if (!result) return nb::make_tuple(nb::none(), wirelink::Error(result.error()));
    return nb::make_tuple(std::move(result).value(), nb::none());
  });
}
