/* SPDX-License-Identifier: Apache-2.0 */
// Generated by WLC. Python headers precede all system headers.
#include <nanobind/nanobind.h>
#include <nanobind/stl/array.h>
#include <nanobind/stl/string.h>
#include <device/client.hpp>
#include <wirelink/version.h>
namespace nb = nanobind;
using namespace device;

namespace {
[[maybe_unused]] InfoRequest read_InfoRequest(nb::handle object) {
  const auto input = nb::cast<nb::tuple>(object);
  if (input.size() != 0) nb::raise_type_error("invalid InfoRequest tuple length");
  InfoRequest output{};
  return output;
}

[[maybe_unused]] nb::tuple write_InfoRequest(const InfoRequest& input) {
  (void)input;
  return nb::make_tuple(
  );
}

[[maybe_unused]] Settings read_Settings(nb::handle object) {
  const auto input = nb::cast<nb::tuple>(object);
  if (input.size() != 10) nb::raise_type_error("invalid Settings tuple length");
  Settings output{};
  if (!input[0].is_none()) {
    output.label = nb::cast<std::string>(input[0]);
  }
    output.enabled = nb::cast<bool>(input[1]);
  if (!input[2].is_none()) {
    output.mode = static_cast<Mode>(nb::cast<std::int32_t>(input[2]));
  }
    output.token = [&] { const auto bytes = nb::cast<nb::bytes>(input[3]); const auto* data = reinterpret_cast<const std::uint8_t*>(bytes.c_str()); return std::vector<std::uint8_t>(data, data + bytes.size()); }();
    output.gains = nb::cast<std::array<float, 3>>(input[4]);
  if (!input[5].is_none()) {
    output.counters = nb::cast<std::array<uint64_t, 2>>(input[5]);
  }
  if (!input[6].is_none()) {
    output.floor = nb::cast<int64_t>(input[6]);
  }
  if (!input[7].is_none()) {
    output.ceiling = nb::cast<uint64_t>(input[7]);
  }
  if (!input[8].is_none()) {
    output.class_ = nb::cast<std::string>(input[8]);
  }
  if (!input[9].is_none()) {
    output.timeout_ = nb::cast<uint16_t>(input[9]);
  }
  return output;
}

[[maybe_unused]] nb::tuple write_Settings(const Settings& input) {
  (void)input;
  return nb::make_tuple(
      (input.label.has_value() ? nb::cast((*input.label)) : nb::none()),
      nb::cast(input.enabled),
      (input.mode.has_value() ? nb::cast(static_cast<std::int32_t>((*input.mode))) : nb::none()),
      nb::object(nb::bytes(reinterpret_cast<const char*>(input.token.data()), input.token.size())),
      nb::cast(input.gains),
      (input.counters.has_value() ? nb::cast((*input.counters)) : nb::none()),
      (input.floor.has_value() ? nb::cast((*input.floor)) : nb::none()),
      (input.ceiling.has_value() ? nb::cast((*input.ceiling)) : nb::none()),
      (input.class_.has_value() ? nb::cast((*input.class_)) : nb::none()),
      (input.timeout_.has_value() ? nb::cast((*input.timeout_)) : nb::none())
  );
}

[[maybe_unused]] InfoResponse read_InfoResponse(nb::handle object) {
  const auto input = nb::cast<nb::tuple>(object);
  if (input.size() != 2) nb::raise_type_error("invalid InfoResponse tuple length");
  InfoResponse output{};
    output.name = nb::cast<std::string>(input[0]);
    output.settings = read_Settings(input[1]);
  return output;
}

[[maybe_unused]] nb::tuple write_InfoResponse(const InfoResponse& input) {
  (void)input;
  return nb::make_tuple(
      nb::cast(input.name),
      nb::object(write_Settings(input.settings))
  );
}

[[maybe_unused]] ConfigureRequest read_ConfigureRequest(nb::handle object) {
  const auto input = nb::cast<nb::tuple>(object);
  if (input.size() != 3) nb::raise_type_error("invalid ConfigureRequest tuple length");
  ConfigureRequest output{};
    output.settings = read_Settings(input[0]);
  if (!input[1].is_none()) {
    output.opaque = [&] { const auto bytes = nb::cast<nb::bytes>(input[1]); const auto* data = reinterpret_cast<const std::uint8_t*>(bytes.c_str()); return std::vector<std::uint8_t>(data, data + bytes.size()); }();
  }
  if (!input[2].is_none()) {
    output.backup = read_Settings(input[2]);
  }
  return output;
}

[[maybe_unused]] nb::tuple write_ConfigureRequest(const ConfigureRequest& input) {
  (void)input;
  return nb::make_tuple(
      nb::object(write_Settings(input.settings)),
      (input.opaque.has_value() ? nb::object(nb::bytes(reinterpret_cast<const char*>((*input.opaque).data()), (*input.opaque).size())) : nb::none()),
      (input.backup.has_value() ? nb::object(write_Settings((*input.backup))) : nb::none())
  );
}

[[maybe_unused]] ConfigureResponse read_ConfigureResponse(nb::handle object) {
  const auto input = nb::cast<nb::tuple>(object);
  if (input.size() != 4) nb::raise_type_error("invalid ConfigureResponse tuple length");
  ConfigureResponse output{};
    output.settings = read_Settings(input[0]);
  if (!input[1].is_none()) {
    output.opaque = [&] { const auto bytes = nb::cast<nb::bytes>(input[1]); const auto* data = reinterpret_cast<const std::uint8_t*>(bytes.c_str()); return std::vector<std::uint8_t>(data, data + bytes.size()); }();
  }
  if (!input[2].is_none()) {
    output.backup = read_Settings(input[2]);
  }
    output.count = nb::cast<uint32_t>(input[3]);
  return output;
}

[[maybe_unused]] nb::tuple write_ConfigureResponse(const ConfigureResponse& input) {
  (void)input;
  return nb::make_tuple(
      nb::object(write_Settings(input.settings)),
      (input.opaque.has_value() ? nb::object(nb::bytes(reinterpret_cast<const char*>((*input.opaque).data()), (*input.opaque).size())) : nb::none()),
      (input.backup.has_value() ? nb::object(write_Settings((*input.backup))) : nb::none()),
      nb::cast(input.count)
  );
}

[[maybe_unused]] Numbers read_Numbers(nb::handle object) {
  const auto input = nb::cast<nb::tuple>(object);
  if (input.size() != 18) nb::raise_type_error("invalid Numbers tuple length");
  Numbers output{};
    output.i8 = nb::cast<int8_t>(input[0]);
    output.u8 = nb::cast<uint8_t>(input[1]);
    output.i16 = nb::cast<int16_t>(input[2]);
    output.u16 = nb::cast<uint16_t>(input[3]);
    output.i32 = nb::cast<int32_t>(input[4]);
    output.u32 = nb::cast<uint32_t>(input[5]);
    output.i64 = nb::cast<int64_t>(input[6]);
    output.u64 = nb::cast<uint64_t>(input[7]);
    output.f32 = nb::cast<uint32_t>(input[8]);
    output.f64 = nb::cast<uint64_t>(input[9]);
    output.single = nb::cast<float>(input[10]);
    output.double_ = nb::cast<double>(input[11]);
  if (!input[12].is_none()) {
    output.doubles = nb::cast<std::array<double, 2>>(input[12]);
  }
    output.words = nb::cast<std::array<uint32_t, 2>>(input[13]);
  if (!input[14].is_none()) {
    output.offset = nb::cast<int64_t>(input[14]);
  }
  if (!input[15].is_none()) {
    output.minimum = nb::cast<int32_t>(input[15]);
  }
  if (!input[16].is_none()) {
    output.flag = nb::cast<bool>(input[16]);
  }
  if (!input[17].is_none()) {
    output.text = nb::cast<std::string>(input[17]);
  }
  return output;
}

[[maybe_unused]] nb::tuple write_Numbers(const Numbers& input) {
  (void)input;
  return nb::make_tuple(
      nb::cast(input.i8),
      nb::cast(input.u8),
      nb::cast(input.i16),
      nb::cast(input.u16),
      nb::cast(input.i32),
      nb::cast(input.u32),
      nb::cast(input.i64),
      nb::cast(input.u64),
      nb::cast(input.f32),
      nb::cast(input.f64),
      nb::cast(input.single),
      nb::cast(input.double_),
      (input.doubles.has_value() ? nb::cast((*input.doubles)) : nb::none()),
      nb::cast(input.words),
      (input.offset.has_value() ? nb::cast((*input.offset)) : nb::none()),
      (input.minimum.has_value() ? nb::cast((*input.minimum)) : nb::none()),
      (input.flag.has_value() ? nb::cast((*input.flag)) : nb::none()),
      (input.text.has_value() ? nb::cast((*input.text)) : nb::none())
  );
}

} // namespace

NB_MODULE(_native, module) {
  module.attr("core_version") = WIRELINK_VERSION_STRING;
  module.attr("codegen_abi") = 32;
  module.attr("binding_api") = 1;
  nb::class_<wirelink::Error>(module, "Error")
      .def_prop_ro("kind", [](const wirelink::Error& e) { return wirelink::error_kind_name(e.kind); })
      .def_prop_ro("status", [](const wirelink::Error& e) { return e.completion.status; })
      .def_prop_ro("rejection", [](const wirelink::Error& e) { return e.completion.rejection; })
      .def_prop_ro("local_error", [](const wirelink::Error& e) { return e.completion.local_error; })
      .def_prop_ro("transport_error", [](const wirelink::Error& e) { return e.completion.transport_error; })
      .def_prop_ro("runtime_error", [](const wirelink::Error& e) { return e.completion.runtime_error; })
      .def_prop_ro("codec_error", [](const wirelink::Error& e) { return e.completion.codec_error; })
      .def_prop_ro("os_error", [](const wirelink::Error& e) { return e.system_error.value(); })
      .def_prop_ro("os_message", [](const wirelink::Error& e) { return e.system_error.message(); });

  nb::class_<device::Client>(module, "Client")
      .def("close", &device::Client::close, nb::call_guard<nb::gil_scoped_release>())
      .def_prop_ro("is_open", &device::Client::is_open)
      .def_prop_ro("local_port", &device::Client::local_port)
      .def("configure", [](device::Client& client, nb::tuple request, std::int64_t timeout_ms) {
        auto owned = read_ConfigureRequest(request);
        auto result = [&] {
          nb::gil_scoped_release release;
          return client.configure(owned, std::chrono::milliseconds(timeout_ms));
        }();
        if (!result) return nb::make_tuple(nb::none(), wirelink::Error(result.error()));
        return nb::make_tuple(write_ConfigureResponse(result.value()), nb::none());
      })
      .def("get_info", [](device::Client& client, nb::tuple request, std::int64_t timeout_ms) {
        auto owned = read_InfoRequest(request);
        auto result = [&] {
          nb::gil_scoped_release release;
          return client.get_info(owned, std::chrono::milliseconds(timeout_ms));
        }();
        if (!result) return nb::make_tuple(nb::none(), wirelink::Error(result.error()));
        return nb::make_tuple(write_InfoResponse(result.value()), nb::none());
      })
      ;
  module.def("connect", [](const std::string& peer_address, std::uint16_t peer_port,
                           const std::string& bind_address, std::uint16_t bind_port) {
    auto result = [&] {
      nb::gil_scoped_release release;
      return device::Client::connect({peer_address, peer_port, bind_address, bind_port});
    }();
    if (!result) return nb::make_tuple(nb::none(), wirelink::Error(result.error()));
    return nb::make_tuple(std::move(result).value(), nb::none());
  });
}
