/* SPDX-License-Identifier: Apache-2.0 */
// Generated by WLC. All fields own their data.
#pragma once
#include <array>
#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace calculator {
struct AddRequest {
  int32_t left{};
  int32_t right{};
};

struct AddResponse {
  int32_t sum{};
};

} // namespace calculator
