# SPDX-License-Identifier: Apache-2.0
add_library(calculator_test_service STATIC service.c)
target_include_directories(calculator_test_service PUBLIC . ../generated)
target_link_libraries(calculator_test_service PUBLIC CalculatorSdk::client Wirelink::asio_udp)
add_executable(calculator_cpp_tests client.cpp)
target_link_libraries(calculator_cpp_tests PRIVATE calculator_test_service)
add_test(NAME calculator_cpp COMMAND calculator_cpp_tests)
set_tests_properties(calculator_cpp PROPERTIES TIMEOUT 30)
add_executable(calculator_c_server server_main.cpp)
target_link_libraries(calculator_c_server PRIVATE calculator_test_service)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
  foreach(target calculator_test_service calculator_cpp_tests calculator_c_server)
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
  endforeach()
endif()
