# SPDX-License-Identifier: Apache-2.0
from typing import Any

core_version: str
codegen_abi: int
binding_api: int

class Error:
    kind: str
    status: int
    rejection: int
    local_error: int
    transport_error: int
    runtime_error: int
    codec_error: int
    os_error: int
    os_message: str

def connect(peer_address: str, peer_port: int, bind_address: str, bind_port: int) -> tuple[Client | None, Error | None]: ...

class Client:
    def close(self) -> None: ...
    @property
    def is_open(self) -> bool: ...
    @property
    def local_port(self) -> int: ...
    def configure(self, request: tuple[Any, ...], timeout_ms: int) -> tuple[tuple[Any, ...] | None, Error | None]: ...
    def get_info(self, request: tuple[Any, ...], timeout_ms: int) -> tuple[tuple[Any, ...] | None, Error | None]: ...
    def configure_async(self, request: tuple[Any, ...], timeout_ms: int) -> tuple[OperationConfigureResponse | None, Error | None]: ...
    def get_info_async(self, request: tuple[Any, ...], timeout_ms: int) -> tuple[OperationInfoResponse | None, Error | None]: ...

def closed_error() -> Error: ...
def queue_full_error() -> Error: ...

class CompletionSignal:
    def __init__(self) -> None: ...
    def wait(self) -> bool: ...
    def stop(self) -> None: ...

class OperationInfoResponse:
    @property
    def done(self) -> bool: ...
    def cancel(self) -> bool: ...
    def notify_on_completion(self, signal: CompletionSignal) -> None: ...
    def result(self) -> tuple[tuple[Any, ...] | None, Error | None]: ...

class OperationConfigureResponse:
    @property
    def done(self) -> bool: ...
    def cancel(self) -> bool: ...
    def notify_on_completion(self, signal: CompletionSignal) -> None: ...
    def result(self) -> tuple[tuple[Any, ...] | None, Error | None]: ...
